---
- name: Copy filter file to data processing pipeline host
  hosts: logstash
  gather_facts: no

  tasks:
#    - debug: var=vars
    - name: Copy filter config file to target /conf.d 
      copy:
        src: "./data/20_filter_91_post_process.logstash.conf"
        dest: "/etc/logstash/elastiflow/conf.d"
        force: yes
      become: yes
      become_user: root