---
- name: Copy filter file to data processing pipeline host
  hosts: logstash
  remote_user: root
  gather_facts: no

  tasks:
    - ping:
    - name: Clear gathered facts from all currently targeted hosts
      meta: clear_facts
    - name: Copy filter config file to target /conf.d
      copy:
        src: "./data/20_filter_91_post_process.logstash.conf"
        dest: "/etc/logstash/elastiflow/conf.d/"
        force: yes
      # become: yes
      # become_user: root