version: '3'

services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    container_name: elasticsearch01
    restart: 'no'
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    network_mode: host
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
    volumes:
      - /var/lib/flow_insight_es01:/usr/share/elasticsearch/data
    environment:
      # JVM Heap size
      #   - this should be at least 2GB for simple testing, receiving only a few flows per second.
      #   - for production environments upto 31GB is recommended.
      ES_JAVA_OPTS: '-Xms12g -Xmx12g'

      cluster.name: flowinsight

      bootstrap.memory_lock: 'true'

      network.host: 0.0.0.0
      http.port: 9200

      action.destructive_requires_name: 'true'

#   flow-elasticsearch02:
#     image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
#     container_name: elasticsearch02
#     restart: 'no'
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
# #    network_mode: host
#     networks:
#       - esnet
#     volumes:
#       - /var/lib/flow_insight:/usr/share/elasticsearch/data
#     environment:
#       # JVM Heap size
#       #   - this should be at least 2GB for simple testing, receiving only a few flows per second.
#       #   - for production environments upto 31GB is recommended.
#       ES_JAVA_OPTS: '-Xms10g -Xmx10g'

#       cluster.name: flowinsight

#       bootstrap.memory_lock: 'true'

#       network.host: 0.0.0.0
#       http.port: 9200

#       action.destructive_requires_name: 'true'

  elastiflow-logstash-oss:
    #image: robcowart/elastiflow-logstash-oss:3.4.1_6.1.3
    build: .
    container_name: elastiflow-logstash-oss
    restart: 'no'
    depends_on:
      - elasticsearch
#    network_mode: host
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - esnet
    volumes:
      - /etc/flow_insight:/usr/share/elasticsearch/data    
    environment:
      # JVM Heap size - this MUST be at least 3GB (4GB preferred)
      LS_JAVA_OPTS: '-Xms10g -Xmx10g'

      # ElastiFlow global configuration
      ELASTIFLOW_DEFAULT_APPID_SRCTYPE: "__UNKNOWN"

      # Name resolution option
      ELASTIFLOW_RESOLVE_IP2HOST: "false"
      ELASTIFLOW_NAMESERVER: "127.0.0.1"
      
      ELASTIFLOW_ES_HOST: elasticsearch01:9200
      ELASTIFLOW_NETFLOW_UDP_WORKERS: 4
      ELASTIFLOW_NETFLOW_UDP_QUEUE_SIZE: 16384
      ELASTIFLOW_NETFLOW_IPV4_PORT: 2055
      ELASTIFLOW_SFLOW_IPV4_PORT: 6343
      ELASTIFLOW_IPFIX_TCP_IPV4_PORT: 4739